CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    qty INTEGER NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT order_items_positive_qty CHECK (qty > 0),
    CONSTRAINT order_items_price_non_negative CHECK (price >= 0)
);
